[package]
name = "tokio-tungstenite"
description = "Tokio binding for Tungstenite, the Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming", "asynchronous", "concurrency"]
keywords = ["websocket", "io", "web"]
authors = ["Daniel Abramov <dabramov@snapview.de>", "Alexey Galakhov <agalakhov@snapview.de>"]
license = "MIT"
homepage = "https://github.com/snapview/tokio-tungstenite"
documentation = "https://docs.rs/tokio-tungstenite/0.9.0"
repository = "https://github.com/snapview/tokio-tungstenite"
version = "0.10.0-alpha.1"
edition = "2018"

[features]
default = ["connect"]
connect = ["stream", "tokio-net"]
tls = ["native-tls", "tokio-tls", "stream", "tungstenite/tls"]
stream = []

[dependencies]
log = "0.4"
futures-preview = "0.3.0-alpha.19"
pin-project = "0.4"
tokio-io = { version = "0.2.0-alpha.6", features = ["util"] }
tokio-net = { version = "0.2.0-alpha.6", optional = true, features = ["tcp"] }

[dependencies.tungstenite]
version = "0.9.2"
default-features = false

[dependencies.native-tls]
optional = true
version = "0.2.0"

[dependencies.tokio-tls]
optional = true
version = "0.3.0-alpha.6"

[dev-dependencies]
tokio = "=0.2.0-alpha.6"
url = "2.0"
env_logger = "0.6"
